# Generated by Django 5.2 on 2025-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vela',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
