# Generated by Django 5.2 on 2025-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_vela_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vela',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='velas/'),
        ),
    ]
